### ISSUE TITLE
Found one security vulnerabilites

### ISSUE THREAD

**Issue by Aju100** [askbuddie/Buddies-movie#2]
![security](https://user-images.githubusercontent.com/29862610/68637555-1442b180-0527-11ea-9042-a52b742bbf06.PNG)
Hey I found one vulnerability of this repo

**Comment by anuraghazra** [comment]
Security vulnerabilities should not be fixed manually, Github's dependaBot will create automatic fixes PR (if enabled)

**Comment by Aju100** [comment]
oooo great

**Comment by mrsudarshanrai** [comment]
BTW thanks for review @Aju100

**Comment by Aju100** [comment]
Thank you Shudarshan brother
