### ISSUE TITLE
Add a prettier configuration

### ISSUE THREAD

**Issue by ashiishme** [askbuddie/Buddies-movie#9]
Add prettier configuration so that the formatting behaviour for this project will be same across all the contributors device.

Please comment down your configuration and let's prepare one from all the suggestion which will be used on this project.

Configuration from my end:

```
{
    "semi": true,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "es5"
}
```

**Comment by mrsudarshanrai** [comment]
@ashiishme I am with your your configuration,  It will surely help different contributors.

**Comment by adarshaacharya** [comment]
@ashiishme I've added above congif on `.prettierrc.json` file , added prettier as dev dependency and 
added `npm run format` as scripts to run formatting. 

Is there any way to format the JSX single quote too ? like in className still there is double quote !

**Comment by ashiishme** [comment]
Officially, Prettier will not format the JSX because it is treated as HTML. So, we have to refactor the project. I think double quotes on class name is fine.

**Comment by adarshaacharya** [comment]
I add this as configuration and now it's showing single quote on jsx too.. 

```json
{
    "semi": true,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "es5",
    "jsxSingleQuote": true
}
```

**Comment by ashiishme** [comment]
I had no idea that the prettier now has this option. That's great. 😄😄

**Comment by adarshaacharya** [comment]
@ashiishme  yeah I also found out recently in its docs.

**Comment by ashiishme** [comment]
@adarshaacharya Okay, thank you bro. I am closing this issue. Your PR is merged. #10
